'use strict';
import { StyleSheet, StatusBar} from 'react-native';
import Dimensions from 'Dimensions';
let { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  main: {
     flex: 1,
     flexDirection:'column',
     alignItems: 'center',
     width:width,
     height:height,
     backgroundColor:'#f7f8fc',
   },
  up:{
    height:78,
    width:width,
    backgroundColor:'#ffffff',
    paddingLeft:15,
    paddingRight:15,
    alignItems:'center',
    justifyContent:'space-between',
    marginTop:10,
    flexDirection:'row'
  },
  up_a:{
    height:60,
    justifyContent:'space-between',
  },
  up_b:{
    flexDirection:'row',
    alignItems:'center',
  },
  up_font:{
    fontSize:13,
    color:'#999999'
  },
  up_font_a:{
    fontSize:13,
    color:'#ffffff'
  },
  middle:{
    height:91,
    width:width,
    paddingTop:10,
    paddingBottom:15,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:15,
    paddingRight:15,
  },
  middle_a:{
    height:66,
    flex:1,
    marginLeft:10,
    paddingTop:2,
    paddingBottom:2,
    justifyContent:'space-between'
  },
  middle_font:{
    fontSize:13,
    color:'#303030',
    padding:0,
  },
  input:{
    fontSize:13,
    color:'#303030',
    padding: 0,
    textAlign:'center'
  },
  middle_font_a:{
    fontSize:15,
    color:'#edaf37'
  },
  down:{
    width:width,
    height:102,
    backgroundColor:'#ffffff',
    paddingRight:15,
    paddingLeft:15,
  },
  down_a:{
    width:width-30,
    height:34,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
  },
  line:{
    borderBottomWidth:1,
    borderColor:'#dddddd',
  },
  down_font:{
    fontSize:15,
    color:'#ef5b5b'
  },
  down_b:{
    flexDirection:'row',
    alignItems:'center',
    minWidth:70,
  },
  jian:{
    height:16,
    width:16,
    borderRadius:2,
    backgroundColor:'#999999',
    justifyContent:'center',
    alignItems:'center'
  },
  jia:{
    height:16,
    width:16,
    borderRadius:2,
    backgroundColor:'#5986ff',
    justifyContent:'center',
    alignItems:'center'
  },
  textInput:{
    flex:1,
  },
  text:{
    width:width,
    height:150,
    backgroundColor:'#ffffff',
    marginTop:10,
    paddingTop:10,
    paddingLeft:15,
    position:'relative'

  },
  text_number:{
    fontSize:13,
    color:'#999999',
    position:'absolute',
    bottom:10,
    right:15,
  },
  button:{
    position:'absolute',
    bottom:0,
    left:0,
    right:0,
    width:width,
    height:49,
    backgroundColor:'#ffffff',
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:15,
  },
  button_font_a:{
    fontSize:13,
    color:'#999999'
  },
  button_font:{
    fontSize:15,
    color:'#edaf37'
  },
  button_font_b:{
    fontSize:15,
    color:'#999999'
  },
  button_a:{
    flex:3,
    flexDirection:'row',
    alignItems:'center',
    height:49,
  },
  button_b:{
    flex:2,
    height:49,
    backgroundColor:'#dddddd',
    justifyContent:'center',
    alignItems:'center'
  },
  button_b_b:{
    flex:2,
    height:49,
    backgroundColor:'#5986ff',
  },
  money:{
    fontSize:12,
    color:'#999999'
  }

});

module.exports = styles
