'use strict';
import { StyleSheet, StatusBar} from 'react-native';
import Dimensions from 'Dimensions';
let { width, height } = Dimensions.get('window');
import color from '../../constant/color'
const styles = StyleSheet.create({
  main: {
     flex: 1,
     flexDirection:'column',
     alignItems: 'center',
     width:width,
     height:height,
     backgroundColor:'#f7f8fc',
   },
   containerStyle:{
    width:width,
    paddingBottom:20,
    alignItems:"center",
    backgroundColor:"#fff",
  },
  dealInfoBox:{
    marginTop:30*width/750,
    marginBottom:15*width/750,
    width:width-30,
    flexDirection:"row",
    justifyContent:"space-between"
  },
  imgBox:{
    width:width,
    height: 450*width/750
  },
  startBox:{
   flexDirection:"row",
   alignItems:"center",
   justifyContent:"space-between"
  },
  dealNumBox:{
    width:width-30,
    flexDirection:"row",
    justifyContent:"space-between",
    marginBottom:30*width/750,
  },
  teamName:{
    fontSize:15,
    color:color.font1C,
  },
  textPrice:{
   fontSize:15,
   color:"#ef5b5b",
  },
  textStart:{
   fontSize:15,
   color:"#edaf37",
  },
  start:{
   height:12,
   width:12,
   marginRight:20*width/750
  },
  textDealNum:{
    fontSize:12,
    color:color.font2C,
  },
  yuTime:{
    flexDirection:"row",
    width:width-30,
    justifyContent:"space-between",
    borderBottomWidth:0.5,
    borderColor:color.border1C
  },
  impression:{
    flexDirection:"row",
    alignItems:'flex-end',
    width:198*width/750,
    marginRight:20*width/750,
    justifyContent:"space-between"
  },
  impressionActive:{
    alignItems:"center",
    width:80*width/750,
    borderBottomWidth:2,
    borderColor:"transparent"
  },
  text_p:{
    fontSize:15,
    color:color.font2C,
    marginBottom:25*width/750
  },
  impressionList:{
    flexDirection:'row',
    flexWrap:'wrap',
    width:width-30,
    justifyContent:"flex-end",
    paddingTop:30*width/750,
    borderBottomWidth:0.5,
    borderColor:color.border1C,
  },
  impressionBtn:{
    height:50*width/750,
    borderWidth:0.5,
    borderColor:color.border1C,
    alignItems:"center",
    justifyContent:"center",
    padding:20*width/750,
    marginLeft:13*width/750,
    marginRight:12.5*width/750,
    marginBottom:30*width/750,
  },
  text:{
    fontSize:13,
    color:color.font2C,
  },
  evaluateBox:{
    marginBottom:20*width/750,
  },
  itemevaluate:{
    width:width,
    padding:30*width/750,
    alignItems:"center",
    justifyContent:"center"
  },
  itemTop:{
    width:width-30,
    alignItems:"center",
    justifyContent:"space-between",
    flexDirection:"row",
    marginBottom:30*width/750
  },
  text1:{
    fontSize:13,
    color:color.font1C,
  },
  itemtr:{
    flex:1,
    alignItems:"flex-end",
    justifyContent:"center",
  },
  allevaluate:{
    width:150*width/750,
    height:50*width/750,
    borderWidth:1,
    borderRadius:2,
    borderColor:color.main1C,
    alignItems:"center",
    justifyContent:"center",
  },
  introductionBox:{
    width:width,
    paddingHorizontal:30*width/750,
    paddingTop:50*width/750,
  },
  rowIntro:{
    width:width-30,
    justifyContent:"space-between",
    flexDirection:"row",
    marginBottom:30*width/750
  },
  introOne:{
    flex:1
  },
  timeBox:{
    height:width/5,
    justifyContent:"space-between",
    flexDirection:"row",
    alignItems:'center',
    width:width-30,
    paddingLeft:100*width/750
  },
  rowContainer:{
    flexDirection:"row",
    paddingLeft:20*width/750,
    paddingBottom:20*width/750,
  },
  timeBg:{
    width:60*width/750,
    height:60*width/750,
    alignItems:"center",
    justifyContent:'center',
    marginRight:10*width/750
  },
  text2:{
    fontSize:15,
    color:color.bar
  },
  ListViewContainer:{
    paddingBottom:60*width/750
  },
  next_action:{
    width:width,
    height:98*width/750,
    backgroundColor:color.main1C,
    justifyContent:"center",
    alignItems:'center',
   },
});

module.exports = styles
