'use strict';
import { StyleSheet, StatusBar} from 'react-native';
import Dimensions from 'Dimensions';
let { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  main: {
     flex: 1,
     flexDirection:'column',
     alignItems: 'center',
     width:width,
     height:height,
     backgroundColor:'#f7f8fc',
   },
   header_box:{
       height:44+StatusBar.currentHeight,
       backgroundColor:'#ffffff',
       marginBottom:10,
   },
   header:{
        position:'relative',
        marginTop:StatusBar.currentHeight,
        width:width,
        height:45,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingRight:15,
        paddingLeft:15,
     },
   matter_k:{
     height:22,
     width:22,
   },
   header_img:{
     height:22,
     width:22,
     position:'relative',
   },
   matter_j:{
     height:8,
     width:8,
     position:'absolute',
     top:0,
     right:0,
   },
   header_font:{
       fontSize:15,
       color:'#303030',
   },
   date:{
     width:width,
     height:115,
     position:'relative',
     justifyContent:'center'
   },
   date_img:{
     height:115,
     width:width,
     position:'absolute',
     top:0,
     right:0,
     bottom:0,
     left:0,
   },
   date_border:{
     width:150,
     height:70,
     borderRadius:5,
     borderWidth:1,
     borderColor:'rgba(255, 255, 255, 0.3)',
     marginLeft:30,
     paddingLeft:15,
     paddingRight:15,
     paddingTop:15,
     paddingBottom:5,
   },
   date_top:{
     height:36,
     flexDirection:'row',
     justifyContent:'space-between',
     alignItems:'center',
     flex:1,
   },
   date_bottom:{
     height:15,
     flex:1,
     flexDirection:'row',
     justifyContent:'space-between',
     alignItems:'center',
   },

   data_activity:{
     flexDirection:'row',
     position:'absolute',
     bottom:10,
     right:15,
     justifyContent:'center',
     alignItems:'center'
   },
   date_font:{
     fontSize:13,
     color:'#ffffff',
   },
   date_img_a:{
     height:13,
     width:13,
     marginLeft:5,
   },
   date_font_a:{
     fontSize:30,
     color:'#ffffff',
     margin:0,
     padding:0
   },
   date_line:{
     borderLeftWidth:1,
     borderLeftColor:'#ffffff',
     height:45,
     width:1,
     position:'absolute',
     top:12,
     left:64,
     opacity:.3
   },
   yuan_a:{
     width:8,
     height:8,
     borderRadius:4,
     borderWidth:2,
     borderColor:'#ffffff',
     position:'absolute',
     top:4,
     right:0
   },
   up:{
     width:width,
     paddingTop:15,
     backgroundColor:'#ffffff',
     paddingLeft:15,
     marginTop:10,
     paddingBottom:15,
   },
   up_a:{
     height:17,
     flexDirection:'row',
     alignItems:'center',
   },
   mine_n:{
     height:17,
     width:17,
     marginRight:5,
   },
   mine_l:{
     height:17,
     width:17,
     marginRight:10,
   },
   list_a:{
     width:width-15,
     minHeight:87,
     paddingTop:10,
     flexDirection:'column',
     position:'relative',
     paddingLeft:22,
   },
   list_up:{
     flexDirection:'row',
   },
   list_font:{
     fontSize:12,
     color:'#999999',
     margin:0,
     padding:0,
   },
   list_font_d:{
     fontSize:13,
     color:'#edaf37',
     margin:0,
     padding:0,
     position:'absolute',
     top:0,
     right:15,
   },
   list_font_e:{
     fontSize:13,
     color:'#5bdba6',
     margin:0,
     padding:0,
     position:'absolute',
     top:14,
     right:15,
   },
   list_font_b:{
     fontSize:13,
     color:'#303030',
     margin:0,
     padding:0,
     lineHeight:15,
   },
   list_middle:{
     height:14,
     width:width-60,
     flexDirection:'row',
     alignItems:'center',
   },
   list_font_c:{
     fontSize:13,
     color:'#999999',
     margin:0,
     padding:0,
   },
   list_font_ccc:{
     fontSize:13,
     color:'#5986ff',
     margin:0,
     padding:0,
   },
   list_font_cc:{
     fontSize:13,
     color:'#edaf37',
   },
   list_line:{
     borderBottomColor:'#dddddd',
     borderBottomWidth:1,
     marginBottom:10
   },
   vote_list:{
     width:width,
     height:87,
     paddingTop:13,
     paddingBottom:13,
     paddingLeft:15,
     paddingRight:15,
     backgroundColor:'#ffffff',
     marginTop:10,
     justifyContent:'space-between'
   },
   vote_up:{
     flexDirection:'row',
     alignItems:'center'
   },
   list_down_a:{
     backgroundColor:'#ffffff',
     width:width,
     height:282,
     flexDirection:'column',
     paddingLeft:15,
     marginTop:10,
     position:'relative',
     alignItems:'center',
   },
   list_text:{
     marginLeft:27,
     width:width-42,
     paddingTop:12,
     height:68,
     flexDirection:'row',
     paddingRight:15,
     borderBottomWidth:1,
     borderBottomColor:'#dddddd',
   },
   list_text_b:{
     width:width-15,
     flexDirection:'row',
     alignItems:'center',
     paddingTop:15,
   },
   list_up_box:{
     width:width-42,
     marginLeft:27,
     height:80,
     flexDirection:'row',
     borderBottomWidth:1,
     borderBottomColor:'#dddddd',
     paddingTop:10,
     paddingBottom:10,
   },
   list_up_a:{
     width:width-100,
     height:60,
     marginLeft:10,
     paddingTop:2,
     paddingBottom:2,
     justifyContent:'space-between',
     flexDirection:'column',
   },
   list_up_b:{
     width:width-127,
     flexDirection:'row',
     justifyContent:'space-between'
   },
   list_up_c:{
     width:width-197,
   },
   list_text_a:{
     marginLeft:10,
     justifyContent:'space-between',
     flexDirection:'row',
   },
   list_all:{
     alignItems:'center',
     flexDirection:'row-reverse',
     width:width-15,
     paddingLeft:15,
     paddingTop:8,
   },
   list_font_g:{
     fontSize:15,
     color:'#edaf37',
   },
   list_button:{
     height:25,
     width:75,
     justifyContent:'center',
     alignItems:'center',
     borderColor:'#dddddd',
     borderWidth:1,
     borderRadius:5,
   },
   list_button_a:{
     height:25,
     width:75,
     justifyContent:'center',
     alignItems:'center',
     borderColor:'#5986ff',
     borderWidth:1,
     borderRadius:5,
   },
   list_button_box:{
     flexDirection:'row',
     justifyContent:'space-between',
     alignItems:'center',
     height:25,
     width:width,
     paddingLeft:32,
     paddingRight:15,
     marginTop:25,
   },
   go_top:{
     width:width,
     height:20,
     justifyContent:'center',
     alignItems:'center',
     position:'absolute',
     bottom:0
   },
   go_top_a:{
     width:40,
     height:20,
     justifyContent:'center',
     alignItems:'center',
     borderTopLeftRadius:5,
     borderTopRightRadius:5,
     marginRight:15,
   },
   icon_e:{
     width:15,
     height:15
   }



});

module.exports = styles
