'use strict';
import { StyleSheet, StatusBar} from 'react-native';
import Dimensions from 'Dimensions';
let { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  main: {
     flex: 1,
     flexDirection:'column',
     alignItems: 'center',
     width:width,
     height:height,
     backgroundColor:'#f7f8fc',
   },
   middle:{
     height:91,
     width:width,
     paddingTop:10,
     paddingBottom:15,
     flexDirection:'row',
     alignItems:'center',
     paddingLeft:15,
     paddingRight:15,
     backgroundColor:'#ffffff',
     marginBottom:10,
     marginTop:10,
   },
   middle_a:{
     height:66,
     flex:1,
     marginLeft:10,
     justifyContent:'space-between'
   },
   middle_font:{
     fontSize:13,
     color:'#303030',
     padding:0,
   },
   middle_font_a:{
     fontSize:15,
     color:'#edaf37'
   },
   list_up_box:{
     width:width,
     height:180,
     padding:15,
     backgroundColor:'#ffffff',
     marginBottom:10,
   },
   list_font:{
     color:'#ffffff',
     fontSize:15,
   },
   order_a:{
     height:22,
     width:22,
     marginRight:10,
   },
   list_middle:{
     height:66,
     width:width-30,
     paddingTop:15,
     paddingBottom:15,
     flexDirection:'column',
     position:'relative',
     borderBottomWidth:1,
     borderBottomColor:'#dddddd'
   },
   list_font_a:{
     fontSize:13,
     color:'#999999',
   },
   icon_b:{
     height:15,
     width:15,
     position:'absolute',
     top:25,
     right:0,
   },
   list_middle_box:{
     width:width,
     backgroundColor:'#ffffff',
     paddingLeft:15,
     paddingRight:15,
     justifyContent:'center'
   },
   list_middle_a:{
     width:width-30,
     paddingTop:15,
     paddingBottom:15,
     borderBottomWidth:1,
     borderBottomColor:'#dddddd'
   },
   list_middle_b:{
     width:width-30,
     paddingTop:15,
     paddingBottom:25,
   },
   list_down:{
     width:width,
     height:232,
     flexDirection:'column',
     backgroundColor:'#ffffff',
     paddingLeft:15,
     paddingRight:15,
     marginTop:10,
     position:'relative',
     alignItems:'center',
     marginBottom:10,
   },
   list_up:{
     width:width-30,
     height:85,
     flexDirection:'row',
     borderBottomWidth:1,
     borderBottomColor:'#dddddd',
     paddingTop:15,
     paddingBottom:10,
   },
   list_font_b:{
     fontSize:13,
     color:'#303030',
   },
   list_up_a:{
     width:width-30,
     height:22,
     justifyContent:'center',
     alignItems:'center',
     flexDirection:'row',
     marginBottom:30,
     marginTop:15
   },
   list_font_c:{
     fontSize:13,
     color:'#edaf37',
   },
   list_font_g:{
     fontSize:15,
     color:'#edaf37',
   },
   list_up_b:{
     width:width-30,
     flexDirection:'row',
     justifyContent:'center',
     height:25,
   },
   list_up_c:{
     width:75,
     height:25,
     justifyContent:'center',
     alignItems:'center',
     borderColor:'#dddddd',
     borderWidth:1,
     marginLeft:12,
     marginRight:12,
     borderRadius:2
   },
   list_up_d:{
     width:75,
     height:25,
     justifyContent:'center',
     alignItems:'center',
     borderColor:'#5986ff',
     borderWidth:1,
     marginLeft:12,
     marginRight:12,
     borderRadius:2
   },
   list_font_f:{
     fontSize:13,
     color:'#999999',
   },
   list_font_j:{
     fontSize:15,
     color:'#303030',
   },
    list_text:{
      width:width-30,
      flexDirection:'row'
    },
  list_text_a:{
    marginLeft:10,
    justifyContent:'space-between',
    flexDirection:'row',
    height:28,
  },
  list_all:{
    alignItems:'center',
    justifyContent:'space-between',
    flexDirection:'row',
    flex:1,
    borderTopWidth:1,
    borderTopColor:'#dddddd',
    width:width-30
  },
  list_font_d:{
    color:'#999999',
    fontSize:15
  },
  list_info:{
    width:330*width/750,


  },
  list_image:{
    height:330*width/750,
    width:330*width/750,
    borderRadius:5,
    marginTop:15
  },
  list_image_a:{
    flex:1,
    flexDirection:'row',
    justifyContent:'space-between',
    width:330*width/750,
    marginTop:10,
  },
  list_info_box:{
    width:width-30,
    flexDirection:'row',
    flexWrap:'wrap',
    justifyContent:'space-between',
  },
  list_bottom:{
    position:'absolute',
    left:0,
    right:0,
    bottom:0,
    backgroundColor:'#f7f8fc',

  },
  list_bottom_a:{
    height:55,
    width:width-10,
    flexDirection:'row-reverse',
    alignItems:'center',
    flex:1,
    backgroundColor:'#ffffff',
    marginTop:10
  },
  list_button:{
    width:75,
    height:25,
    justifyContent:'center',
    alignItems:'center',
    borderColor:'#dddddd',
    borderWidth:1,
    borderRadius:5,
    marginLeft:5,
    marginRight:5
  },
  list_button_a:{
    width:75,
    height:25,
    justifyContent:'center',
    alignItems:'center',
    borderColor:'#5986ff',
    borderWidth:1,
    borderRadius:5,
    marginLeft:5,
    marginRight:5
  },
  list_button_font:{
    fontSize:13,
    color:'#5986ff'
  }





});

module.exports = styles
